### PR TITLE
Week1 second page - Add new files (photos.html and style-photos.css)

### PR DESCRIPTION
**Pull request by sebagabs**
Add two new files: `photos.html` and `style-photos.css`, plus add 10 new photos in the `/images` directory.

### CODE REVIEW

**Comment by GoogleyGabriel** [comment]
Your description says you added two new files: `photos.html` and `style-photos.css` (and pics in the image directory), but I also see changes to some other files, like pom.xml and index.html. Was that intended?

**Comment by sebagabs** [comment]
> Your description says you added two new files: `photos.html` and `style-photos.css` (and pics in the image directory), but I also see changes to some other files, like pom.xml and index.html. Was that intended?

I think it was intentional; I modified the `pom.xml` so that the page could be published and I think the `index.html` was to link correctly to `photos.html`. I must've done it all in the same commit and forgot about detailing those two changes; the `pom.xml` change was specified in the tutorial so I just did it along with the rest.

**Review by SofiaPSU — APPROVED** [review]
I like that you made a random fact section! Overall, good job!

**Comment by GoogleyGabriel** [comment]
> > Your description says you added two new files: `photos.html` and `style-photos.css` (and pics in the image directory), but I also see changes to some other files, like pom.xml and index.html. Was that intended?
> 
> I think it was intentional; I modified the `pom.xml` so that the page could be published and I think the `index.html` was to link correctly to `photos.html`. I must've done it all in the same commit and forgot about detailing those two changes; the `pom.xml` change was specified in the tutorial so I just did it along with the rest.

Ah -- I see. Make sure to document that in your PR descriptions. If there are autogenerated files, you should mention it in the description as well. Essentially, all the files should be accounted for. You can do catch all for various files, like "all *.xml files were auto-generated by running _________."

**Review by GoogleyGabriel — APPROVED** [review]

**Pull request merged**
